config/routes.rb
Ror4::Application.routes.draw do

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :groups
    resources :pictures
    resources :products
    resources :categories
    resources :sections
    resources :articles
    resources :contents

    post 'upload',          to: 'pictures', as: :upload

    get  'dates',           to: 'pages',    as: :dates
    get  'debug',           to: 'pages',    as: :debug
    get  'init',            to: 'pages',    as: :init
    get  'form_validation', to: 'pages',    as: :form_validation
    post 'form_validation', to: 'pages'
    get  'messages/index'
    get  'notification',    to: 'messages', as: :notification
    post 'notification',    to: 'messages'
    get  'multi_form',      to: 'pages',    as: :multi_form
    get  'net_http',        to: 'pages',    as: :net_http
    post 'send_msg',        to: 'pages',    as: :send_msg
    get  'sf_sample',       to: 'pages',    as: :sf_page
    get  'sexi_tips',       to: 'pages',    as: :sexi_tips
    post 'show_year',       to: 'pages',    as: :show_year
    post 'update_year',     to: 'pages',    as: :update_year
    get  'yaml_files',      to: 'pages',    as: :yaml_file
    get  'zt_mailer',       to: 'pages',    as: :zt_mailer

    get 'zt_group_cmt', to: 'pages',    as: :zt_group_cmt
    get 'zt_i18n_cmt',  to: 'pages',    as: :zt_i18n_cmt

    root to: "pages#home"
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :article
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  require 'open-uri'
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    url = Article.find(@content.article_id).url
    @content.doc = open(url).read

    respond_to do |format|
      if @content.save!
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:article_id, :doc)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, url: (@content.id.nil? ? contents_path : content_path(id: @content)) do |f| %>

  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%=  f.collection_select :article_id, Article.all, :id, :title, include_blank: false %>

  </div>
  <div class="field">
    <%= f.label :doc %><br>
    <%= f.text_area :doc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to t(:show), content_path(id: @content) %> |
<%= link_to t(:back), contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <!--th>Doc</th-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.article_id %></td>
        <!--td><%#= content.doc %></td-->
        <td><%= link_to image_tag('buttons/show.png',   alt: 'show',    title: t(:show)),    content_url(id: content) %></td>
        <td><%= link_to image_tag('buttons/edit.png',   alt: 'edit',    title: t(:edit)),    edit_content_url(id: content) %></td>
        <td><%= link_to image_tag('buttons/delete.png', alt: 'destroy', title: t(:destroy)), content_url(id: content), method: :delete, data: {confirm: t(:sure_message)} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to t(:new_content), new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to t(:back), contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @content.article %>
</p>

<p>
  <strong>Doc:</strong>
  <%= @content.doc.html_safe %>
</p>

<%= link_to 'Edit', edit_content_path(id: @content) %> |
<%= link_to 'Back', contents_path %>