config/routes.rb
Ror4::Application.routes.draw do

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :groups
    resources :pictures
    resources :products
    resources :categories
    resources :sections
    resources :articles
    resources :contents

    post 'upload',          to: 'pictures', as: :upload

    get  'dates',           to: 'pages',    as: :dates
    get  'debug',           to: 'pages',    as: :debug
    get  'init',            to: 'pages',    as: :init
    get  'form_validation', to: 'pages',    as: :form_validation
    post 'form_validation', to: 'pages'
    get  'messages/index'
    get  'notification',    to: 'messages', as: :notification
    post 'notification',    to: 'messages'
    get  'multi_form',      to: 'pages',    as: :multi_form
    get  'net_http',        to: 'pages',    as: :net_http
    post 'send_msg',        to: 'pages',    as: :send_msg
    get  'sf_sample',       to: 'pages',    as: :sf_page
    get  'sexi_tips',       to: 'pages',    as: :sexi_tips
    post 'show_year',       to: 'pages',    as: :show_year
    post 'update_year',     to: 'pages',    as: :update_year
    get  'yaml_files',      to: 'pages',    as: :yaml_file
    get  'zt_mailer',       to: 'pages',    as: :zt_mailer

    get 'zt_group_cmt', to: 'pages',    as: :zt_group_cmt
    get 'zt_i18n_cmt',  to: 'pages',    as: :zt_i18n_cmt

    root to: "pages#home"
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_one :content
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:authors, :title, :issue_date, :url)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, url: (@article.id.nil? ? articles_path : article_path(id: @article)) do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :authors %><br>
    <%= f.text_field :authors %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :issue_date %><br>
    <%= f.date_select :issue_date %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to t(:show), article_path(id: @article) %> |
<%= link_to t(:back), articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Authors</th>
      <th>Title</th>
      <th>Issue date</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.authors %></td>
        <td><%= article.title %></td>
        <td><%= article.issue_date %></td>
        <td><%= article.url %></td>
        <td><%= link_to image_tag('buttons/show.png',   alt: 'show',    title: t(:show)),    article_url(id: article) %></td>
        <td><%= link_to image_tag('buttons/edit.png',   alt: 'edit',    title: t(:edit)),    edit_article_url(id: article) %></td>
        <td><%= link_to image_tag('buttons/delete.png', alt: 'destroy', title: t(:destroy)), article_url(id: article), method: :delete, data: {confirm: t(:sure_message)} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to t(:new_article), new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to t(:back), articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Authors:</strong>
  <%= @article.authors %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Issue date:</strong>
  <%= @article.issue_date %>
</p>

<p>
  <strong>Url:</strong>
  <%= @article.url %>
</p>

<%= link_to t(:edit), edit_article_url(id: @article) %> |
<%= link_to t(:back), groups_path %>