config/routes.rb
Ror4::Application.routes.draw do

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :groups
    resources :pictures
    resources :products
    resources :categories
    resources :sections
    resources :articles
    resources :contents

    post 'upload',          to: 'pictures', as: :upload

    get  'dates',           to: 'pages',    as: :dates
    get  'debug',           to: 'pages',    as: :debug
    get  'init',            to: 'pages',    as: :init
    get  'form_validation', to: 'pages',    as: :form_validation
    post 'form_validation', to: 'pages'
    get  'messages/index'
    get  'notification',    to: 'messages', as: :notification
    post 'notification',    to: 'messages'
    get  'multi_form',      to: 'pages',    as: :multi_form
    get  'net_http',        to: 'pages',    as: :net_http
    post 'send_msg',        to: 'pages',    as: :send_msg
    get  'sf_sample',       to: 'pages',    as: :sf_page
    get  'sexi_tips',       to: 'pages',    as: :sexi_tips
    post 'show_year',       to: 'pages',    as: :show_year
    post 'update_year',     to: 'pages',    as: :update_year
    get  'yaml_files',      to: 'pages',    as: :yaml_file
    get  'zt_mailer',       to: 'pages',    as: :zt_mailer

    get 'zt_group_cmt', to: 'pages',    as: :zt_group_cmt
    get 'zt_i18n_cmt',  to: 'pages',    as: :zt_i18n_cmt

    root to: "pages#home"
  end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

  get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name,  presence: true, uniqueness: true
  validates :title, presence: true
end

app/controllers/groups_controller.rb
################################################################################
#   Standard scaffold Controller is modified to meet I18n requirements
#
#   15.12.2013  page titles
#   03.01.2014  Last update (simplify code: no respond_to)
################################################################################
class GroupsController < ApplicationController

  before_filter :set_locale     #ZT
  before_action :set_group,  only: [:show, :edit, :update, :destroy]

# respond_to :html, :xml, :json   # ZT: for future usage

  # GET /groups
  def index
    @groups      = Group.all
    @page_title  = :groups
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group      = Group.new
    @page_title = :new_group
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_url(id: @group), notice: t('activerecord.successful.messages.created', model: @group.class.model_name.human)
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to group_url(id: @group), notice: t('activerecord.successful.messages.updated', model: @group.class.model_name.human)
    else
      render action: 'edit'
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url
  end

  # Use callbacks to share common setup or constraints between actions.
  private

    ############################################################################
    # ZT: this method is good to be used when I18n is applied (see page zt_i18n.html):
    #     Use it to replace code: @group = Group.find(params[:id])
    ############################################################################
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
#     params.require(:group).permit(:name, :title)  # ZT
      params.require(:group).permit(:title)         # ZT: only title is white-listed for mass assignment
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, url: (@group.id.nil? ? groups_path : group_path(id: @group)) do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1><%= t 'activerecord.handling.editing', model: @group.class.model_name.human %></h1>

<%= render 'form' %>

<%= link_to t(:show), group_path(id: @group) %> |
<%= link_to t(:back), groups_path %>

app/views/groups/index.html.erb
<p>
  <%= link_to (t :comments), "/#{I18n.locale}/zt_group_cmt" %>
</p>

<h1><%= t :listing_groups %></h1>

<table>
  <thead>
    <tr>
      <th><%= t :name %></th>
      <th><%= t :title %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.title %></td>
        <td><%= link_to image_tag('buttons/show.png',   alt: 'show',    title: t(:show)),    group_url(id: group) %></td>
        <td><%= link_to image_tag('buttons/edit.png',   alt: 'edit',    title: t(:edit)),    edit_group_url(id: group) %></td>
        <td><%= link_to image_tag('buttons/delete.png', alt: 'destroy', title: t(:destroy)), group_url(id: group), method: :delete, data: {confirm: t(:sure_message)} %></td>

        <%# Text buttons are obsolete here (replaced with images)%>
        <!--td><%#= link_to t(:show),    group_url(id: group) %></td==>
        <!--td><%#= link_to t(:edit),    edit_group_url(id: group) %></td-->
        <!--td><%#= link_to t(:destroy), group_url(id: group), method: :delete, data: { confirm: t(:sure_message) } %></td-->
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to t(:new_group), new_group_path %>

app/views/groups/new.html.erb
<h1><%= t 'activerecord.handling.new', model: @group.class.model_name.human %></h1>

<%= render 'form' %>

<%= link_to t(:back), groups_path %>

app/views/groups/show.html.erb
<h1><%= t(@group.class.model_name.human) %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= t :name %>:</strong>
  <%= @group.name %>
</p>

<p>
  <strong><%= t :title %>:</strong>
  <%= @group.title %>
</p>

<%= link_to t(:edit), edit_group_url(id: @group) %> |
<%= link_to t(:back), groups_path %>